server:
  port: 8001

spring:
  application:
    name: cloud-business-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.7:8800

seata:
  # enabled: true
  # application-id: ${spring.application.name}
  tx-service-group: sample-seata-service-group
  # enable-auto-data-source-proxy: true
  # use-jdk-proxy: false
  # excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  service:
    vgroup-mapping:
      sample-seata-service-group: default
    # enable-degrade: false
    # disable-global-transaction: false
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.7:8800
      group : SEATA_GROUP
      application: seata-server
      # namespace:
      # username: ""
      # password: ""
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.7:8800
      group: SEATA_GROUP
      # namespace:
      # username: ""
      # password: ""
#  client:
#    rm:
#      async-commit-buffer-limit: 1000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      saga-branch-register-enable: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#      commit-retry-count: 5
#      rollback-retry-count: 5
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#      only-care-update-columns: true
#    log:
#      exceptionRate: 100
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true

feign:
  client:
    config:
      default:
        connect-timeout: 6000
        read-timeout: 6000

management:
  endpoints:
    web:
      exposure:
        include:
        - nacos-discovery

logging:
  level:
    root: info

---

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_samples?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sample.springcloud.entity