server:
  port: 8001

spring:
  application:
    # 注册进注册中心的名称
    name: cloud-provider-payment

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 # 心跳间隔，默认30秒
    lease-expiration-duration-in-seconds: 90 # 心跳超时间隔，默认90秒
  client:
    # 将自己的服务信息注册进eureka注册中心，可被其它服务获取到
    register-with-eureka: true
    # 从eureka注册中心获取服务信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.sample.com:7001/eureka/,
                   http://eureka7002.sample.com:7002/eureka/,
                   http://eureka7003.sample.com:7003/eureka/

logging:
  level:
    root: info

---

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_samples?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sample.springcloud.entity