server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.sample.com:7001/eureka/,
                   http://eureka7002.sample.com:7002/eureka/,
                   http://eureka7003.sample.com:7003/eureka/

# 开启feign支持hystrix
feign:
  hystrix:
    enabled: true

# （新版本不这样做了，参照官方文档）设置feign客户端超时时间，因为feign底层使用的ribbon，超时时间也是通过ribbon的属性控制
ribbon:
  # 建立连接超时时间
  ConnectTimeout: 5000
  # 请求超时时间
  ReadTimeout: 5000

logging:
  level:
    root: info