server:
  port: 8004

spring:
  application:
    name: cloud-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.7:8800

seata:
  tx-service-group: sample-seata-service-group
  service:
    vgroup-mapping:
      sample-seata-service-group: default
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.1.7:8800
      group : SEATA_GROUP
      application: seata-server
      # namespace:
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.7:8800
      group: SEATA_GROUP
      # namespace:

feign:
  client:
    config:
      default:
        connect-timeout: 6000
        read-timeout: 6000

management:
  endpoints:
    web:
      exposure:
        include:
        - nacos-discovery

logging:
  level:
    root: info

---

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_samples?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sample.springcloud.entity