server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        # Nacos集群SLB入口地址，使用VIP/Nginx时还需要使用TCP转发暴露偏移量1000的端口用于客户端gRPC请求服务端
        server-addr: 192.168.1.7:8800 # 本例使用端口8800，客户端还会gRCP请求服务端9800端口
        # namespace: '' # 命名空间ID，默认使用public保留空间（注意此时值为空，不要写public），常用于不同环境（dev、prod）的资源（配置、服务）隔离
        # group: DEFAULT_GROUP
        # service: ${spring.application.name}
        # cluster-name: DEFAULT # 虚拟集群，同一个服务的所有实例组成一个默认集群，集群可以被进一步按需求划分，划分的单位可以是虚拟集群
        # weight: 1 # 实例级别的权重，数值越大分配的流量越大

management:
  endpoints:
    web:
      exposure:
        include:
        - nacos-discovery # Nacos Discovery提供的Endpoint

logging:
  level:
    root: info